server:
  port: 21434
spring:
  application:
    name: ollama-agent
  datasource:
    url: jdbc:h2:mem:ollama-agent
    driver-class-name: org.h2.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:/data/init.sql
      data-locations: classpath:/data/data.sql

