server:
  port: 21434
  servlet:
    session:
      timeout: 1D
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  application:
    name: jllama
  datasource:
    url: jdbc:h2:file:~/.jllama/db;AUTO_SERVER=TRUE;MODE=MySQL;DB_CLOSE_ON_EXIT=TRUE;INIT=RUNSCRIPT FROM 'classpath:/data/init.sql'
    driver-class-name: org.h2.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml

jllama:
  auth:
    ignore-paths: ${spring.h2.console.path},/app/**,*.css,*.js,/favicon.ico
  model:
    save-dir: ${user.home}/.jllama/models
  llama-cpu-dir: ${user.dir}/llama/%platform%
  llama-log-dir: ${user.home}/.jllama/logs
  gpu:
    enable: false
    llama-dir: #${user.dir}/llama/llama-b4893-bin-win-cu12.4-x64
  quantize:
    supportedTypes:
      - Q4_0
      - Q4_1
      - Q5_0
      - Q5_1
      - IQ2_XXS
      - IQ2_XS
      - IQ2_S
      - IQ2_M
      - IQ1_S
      - IQ1_M
      - TQ1_0
      - TQ2_0
      - Q2_K
      - Q2_K_S
      - IQ3_XXS
      - IQ3_S
      - IQ3_M
      - Q3_K
      - IQ3_XS
      - Q3_K_S
      - Q3_K_M
      - Q3_K_L
      - IQ4_NL
      - IQ4_XS
      - Q4_K
      - Q4_K_S
      - Q4_K_M
      - Q5_K
      - Q5_K_S
      - Q5_K_M
      - Q6_K
      - Q8_0
      - F16
      - BF16
      - F32
      - COPY
  checkUpdate:
    cpp-url: https://github.com/ggml-org/llama.cpp/releases
    cpp-xpath: '//*[@id="repo-content-pjax-container"]/div/div[3]/section[1]/div/div[1]/div[3]/a/div/span'
    factory-url: https://github.com/hiyouga/LLaMA-Factory/releases
    factory-xpath: '//*[@id="repo-content-pjax-container"]/div/div[3]/section[1]/div/div[1]/div[3]/a/div/span'
logging:
  file:
    max-history: 7
    max-size: 10MB
    name: ${user.home}/.jllama/logs/app.log
  level:
    root: info
    com.jllama: debug
