start javaw -jar -Dspring.config.location=./application.yml --module-path ".\javafx-sdk\win\lib" --add-modules javafx.controls,javafx.web jllama.jar -Dstartbrowser=true
echo Jllama is starting...
timeout /t 5 /nobreak > nul
echo Jllama is running...